# Generated by Django 2.1.3 on 2018-11-25 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('htmlUrl', models.URLField(blank=True, max_length=1024)),
                ('xmlUrl', models.URLField(max_length=1024)),
                ('updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(blank=True, max_length=1024)),
                ('link', models.URLField(blank=True, max_length=1024)),
                ('published', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('guid', models.CharField(max_length=1024)),
                ('content', models.TextField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feeds.Feed')),
                ('visitedBy', models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Meta',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='feeds.Category')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='feeds.Feed')),
            ],
        ),
    ]
